name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]   # change if your default branch is different
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false     # you're cloning the theme manually below
          fetch-depth: 0

      # Pull the theme (or use a submodule instead)
      - name: Sync Theme
        run: |
          rm -rf themes/paper
          git clone --branch main https://github.com/nanxiaobei/hugo-paper.git themes/paper

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      # ---- Tailwind/PostCSS toolchain ----
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install --no-audit --no-fund
          else
            echo "No package.json found; skipping Node install."
          fi

      # ---- Hugo build (extended) ----
      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.0'   # match your local version
          extended: true

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          # If you have a CSS build script, run it (optional)
          if npm pkg get scripts.build:css >/dev/null 2>&1; then
            npm run build:css
          fi
          hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

